import type {
  ProfilConfig,
  ProduitConfig,
  SectionCollecte,
  DefinitionChamp,
} from "./studioTypes";

export const initialProfils: ProfilConfig[] = [
  {
    code: "SALARIE",
    libelle: "Salarié / Fonctionnaire",
    description: "Employés du secteur public, parapublic ou privé formel avec salaire régulier",
    icone: "Briefcase",
    type_demandeur: "PHYSIQUE",
    actif: true,
  },
  {
    code: "AGRICULTEUR",
    libelle: "Agriculteur / Producteur",
    description: "Producteurs céréaliers, cotonniers, maraîchers et arboriculteurs",
    icone: "Sprout",
    type_demandeur: "PHYSIQUE",
    actif: true,
  },
  {
    code: "COMMERCANT",
    libelle: "Commerçant de Marché",
    description: "Commerces de détail, demi-gros sur marchés urbains et ruraux",
    icone: "Store",
    type_demandeur: "PHYSIQUE",
    actif: true,
  },
  {
    code: "PME",
    libelle: "Petite & Moyenne Entreprise",
    description: "Entreprises structurées avec comptabilité, personnel permanent et RCCM",
    icone: "Building2",
    type_demandeur: "MORALE",
    actif: true,
  },
  {
    code: "PERSONNE_MORALE",
    libelle: "Société / GIE / Coopérative",
    description: "Personnes morales, SARL, coopératives agricoles et groupements d'intérêt",
    icone: "Users2",
    type_demandeur: "MORALE",
    actif: true,
  },
];

export const initialProduits: ProduitConfig[] = [
  {
    code: "CRED_SALARIE",
    libelle: "Prêt Équipement & Consommation Salarié",
    profil_code: "SALARIE",
    montant_min: 300000,
    montant_max: 5000000,
    duree_min_mois: 6,
    duree_max_mois: 24,
    taux_annuel: 11.5,
    description: "Financement pour salariés avec domiciliation irrévocable de salaire (quotité <= 33%)",
  },
  {
    code: "CRED_CAMPAGNE",
    libelle: "Crédit Campagne Agricole & Intrants",
    profil_code: "AGRICULTEUR",
    montant_min: 500000,
    montant_max: 10000000,
    duree_min_mois: 6,
    duree_max_mois: 12,
    taux_annuel: 9.5,
    description: "Financement des semences, engrais et travaux avec remboursement in fine après récolte",
  },
  {
    code: "CRED_COMMERCE",
    libelle: "Ligne Trésorerie & Renouvellement Stock",
    profil_code: "COMMERCANT",
    montant_min: 1000000,
    montant_max: 15000000,
    duree_min_mois: 3,
    duree_max_mois: 18,
    taux_annuel: 12.0,
    description: "Fonds de roulement pour approvisionnement marchandise sur foires et boutiques",
  },
  {
    code: "CRED_PME_FDR",
    libelle: "Fonds de Roulement PME & Exploitation",
    profil_code: "PME",
    montant_min: 5000000,
    montant_max: 50000000,
    duree_min_mois: 12,
    duree_max_mois: 36,
    taux_annuel: 10.0,
    description: "Ligne de trésorerie moyen terme pour PME structurée (couverture dette >= 200%)",
  },
];

export const initialSections: SectionCollecte[] = [
  {
    id: "sec_identite",
    code: "IDENTITE",
    titre: "Identification de l'Emprunteur",
    description: "État civil, pièces d'identité officielles et coordonnées",
    ordre: 1,
    profils_applicables: ["SALARIE", "AGRICULTEUR", "COMMERCANT", "PME", "PERSONNE_MORALE"],
  },
  {
    id: "sec_emploi",
    code: "EMPLOI",
    titre: "Emploi & Salaire",
    description: "Situation professionnelle, employeur et conditions de travail",
    ordre: 2,
    profils_applicables: ["SALARIE"],
  },
  {
    id: "sec_agricole",
    code: "EXPLOITATION_AGRICOLE",
    titre: "Exploitation Agricole & Terres",
    description: "Superficies cultivées, intrants, type de cultures et calendrier",
    ordre: 2,
    profils_applicables: ["AGRICULTEUR"],
  },
  {
    id: "sec_activite_pme",
    code: "ACTIVITE_ENTREPRISE",
    titre: "Activité & Données Entreprise",
    description: "Raison sociale, immatriculation RCCM, NIF et chiffre d'affaires",
    ordre: 2,
    profils_applicables: ["PME", "PERSONNE_MORALE", "COMMERCANT"],
  },
  {
    id: "sec_menage",
    code: "LOGEMENT_MENAGE",
    titre: "Logement & Charges du Ménage",
    description: "Statut d'occupation, loyer et personnes à charge",
    ordre: 3,
    profils_applicables: ["SALARIE", "AGRICULTEUR", "COMMERCANT"],
  },
  {
    id: "sec_demande",
    code: "DEMANDE_CREDIT",
    titre: "Détail du Prêt Sollicité",
    description: "Montant, durée souhaitée et destination des fonds",
    ordre: 4,
    profils_applicables: ["SALARIE", "AGRICULTEUR", "COMMERCANT", "PME", "PERSONNE_MORALE"],
  },
];

export const initialChamps: DefinitionChamp[] = [
  // SECTION IDENTITE
  {
    id: "c_nom",
    code: "nom_prenom",
    libelle: "Nom & Prénom(s)",
    section_id: "sec_identite",
    type_donnee: "TEXTE",
    categorie: "IDENTIFICATION",
    temporalite: "STATIQUE",
    role_analytique: "IDENTIFICATION_SEULE",
    niveau_verification: "VERIFIE",
    sensibilite: "PERSONNELLE",
    obligatoire: true,
    actif: true,
    profils_applicables: ["TOUS"],
    placeholder: "Ex: Fatou Traoré",
    piece_justificative_attendue: "CNI Biométrique / Carte NINA",
  },
  {
    id: "c_telephone",
    code: "telephone_principal",
    libelle: "Numéro de Téléphone Mobile",
    section_id: "sec_identite",
    type_donnee: "TELEPHONE",
    categorie: "CONTACT",
    temporalite: "VALEUR_ACTUELLE",
    role_analytique: "IDENTIFICATION_SEULE",
    niveau_verification: "VERIFIE",
    sensibilite: "PERSONNELLE",
    obligatoire: true,
    actif: true,
    profils_applicables: ["TOUS"],
    placeholder: "+223 76 54 32 10",
  },
  {
    id: "c_piece_type",
    code: "type_piece_identite",
    libelle: "Type de Pièce d'Identité",
    section_id: "sec_identite",
    type_donnee: "CHOIX_SIMPLE",
    categorie: "IDENTIFICATION",
    temporalite: "STATIQUE",
    role_analytique: "IDENTIFICATION_SEULE",
    niveau_verification: "VERIFIE",
    sensibilite: "PERSONNELLE",
    obligatoire: true,
    actif: true,
    profils_applicables: ["TOUS"],
    options: ["CNI Biométrique / CEDEAO", "Carte NINA", "Passeport", "Carte Consulaire"],
  },

  // SECTION EMPLOI (SALARIE)
  {
    id: "c_employeur",
    code: "nom_employeur",
    libelle: "Nom de l'Employeur / Ministère",
    section_id: "sec_emploi",
    type_donnee: "TEXTE",
    categorie: "EMPLOI",
    temporalite: "VALEUR_ACTUELLE",
    role_analytique: "SEGMENTATION",
    niveau_verification: "DECLARE",
    sensibilite: "NORMALE",
    obligatoire: true,
    actif: true,
    profils_applicables: ["SALARIE"],
    placeholder: "Ex: Ministère de l'Éducation Nationale",
  },
  {
    id: "c_type_contrat",
    code: "type_contrat_travail",
    libelle: "Nature du Contrat de Travail",
    section_id: "sec_emploi",
    type_donnee: "CHOIX_SIMPLE",
    categorie: "EMPLOI",
    temporalite: "STATIQUE",
    role_analytique: "ENTREE_REGLE",
    niveau_verification: "VERIFIE",
    sensibilite: "NORMALE",
    obligatoire: true,
    actif: true,
    profils_applicables: ["SALARIE"],
    options: ["Fonctionnaire Titulaire", "Contrat à Durée Indéterminée (CDI)", "Contrat à Durée Déterminée (CDD)", "Contractuel"],
  },
  {
    id: "c_salaire",
    code: "salaire_net_mensuel",
    libelle: "Salaire Net Mensuel (FCFA)",
    section_id: "sec_emploi",
    type_donnee: "MONTANT",
    categorie: "FINANCIER",
    temporalite: "VALEUR_ACTUELLE",
    role_analytique: "VARIABLE_CANDIDATE",
    niveau_verification: "VERIFIE",
    sensibilite: "FINANCIERE",
    obligatoire: true,
    actif: true,
    profils_applicables: ["SALARIE"],
    placeholder: "350 000",
    piece_justificative_attendue: "Dernier bulletin de salaire cacheté",
  },
  {
    id: "c_domiciliation",
    code: "domiciliation_salaire_kafo",
    libelle: "Le salaire est-il domicilié à la caisse ?",
    section_id: "sec_emploi",
    type_donnee: "BOOLEEN",
    categorie: "FINANCIER",
    temporalite: "VALEUR_ACTUELLE",
    role_analytique: "ENTREE_REGLE",
    niveau_verification: "VERIFIE",
    sensibilite: "FINANCIERE",
    obligatoire: true,
    actif: true,
    profils_applicables: ["SALARIE"],
  },

  // SECTION AGRICOLE (AGRICULTEUR)
  {
    id: "c_culture",
    code: "culture_principale",
    libelle: "Culture Principale Prévue",
    section_id: "sec_agricole",
    type_donnee: "CHOIX_SIMPLE",
    categorie: "ACTIVITE",
    temporalite: "PERIODE",
    role_analytique: "SEGMENTATION",
    niveau_verification: "DECLARE",
    sensibilite: "NORMALE",
    obligatoire: true,
    actif: true,
    profils_applicables: ["AGRICULTEUR"],
    options: ["Riz irrigué", "Mil / Sorgho", "Maïs", "Coton", "Arachide", "Maraîchage (Échalote/Oignon)"],
  },
  {
    id: "c_superficie",
    code: "superficie_cultivee_ha",
    libelle: "Superficie Cultivée (Hectares)",
    section_id: "sec_agricole",
    type_donnee: "DECIMAL",
    categorie: "ACTIVITE",
    temporalite: "PERIODE",
    role_analytique: "VARIABLE_CANDIDATE",
    niveau_verification: "OBSERVE",
    sensibilite: "NORMALE",
    obligatoire: true,
    actif: true,
    profils_applicables: ["AGRICULTEUR"],
    placeholder: "Ex: 4.5",
  },
  {
    id: "c_intrants",
    code: "cout_intrants_estime",
    libelle: "Coût Estimé des Semences et Engrais (FCFA)",
    section_id: "sec_agricole",
    type_donnee: "MONTANT",
    categorie: "FINANCIER",
    temporalite: "PERIODE",
    role_analytique: "VARIABLE_CANDIDATE",
    niveau_verification: "DECLARE",
    sensibilite: "FINANCIERE",
    obligatoire: true,
    actif: true,
    profils_applicables: ["AGRICULTEUR"],
    placeholder: "Ex: 850 000",
  },
  {
    id: "c_recolte",
    code: "recolte_attendue_tonnes",
    libelle: "Volume de Récolte Attendu (Tonnes / Sacs)",
    section_id: "sec_agricole",
    type_donnee: "DECIMAL",
    categorie: "ACTIVITE",
    temporalite: "PERIODE",
    role_analytique: "VARIABLE_CANDIDATE",
    niveau_verification: "DECLARE",
    sensibilite: "NORMALE",
    obligatoire: true,
    actif: true,
    profils_applicables: ["AGRICULTEUR"],
  },

  // SECTION ACTIVITE ENTREPRISE / PME / COMMERCANT
  {
    id: "c_raison_sociale",
    code: "raison_sociale",
    libelle: "Raison Sociale / Enseigne",
    section_id: "sec_activite_pme",
    type_donnee: "TEXTE",
    categorie: "IDENTIFICATION",
    temporalite: "STATIQUE",
    role_analytique: "IDENTIFICATION_SEULE",
    niveau_verification: "VERIFIE",
    sensibilite: "NORMALE",
    obligatoire: true,
    actif: true,
    profils_applicables: ["PME", "PERSONNE_MORALE", "COMMERCANT"],
    placeholder: "Ex: Société Sahélienne de Distribution (SODIS SARL)",
  },
  {
    id: "c_rccm",
    code: "numero_rccm",
    libelle: "Numéro RCCM / Registre",
    section_id: "sec_activite_pme",
    type_donnee: "TEXTE",
    categorie: "IDENTIFICATION",
    temporalite: "STATIQUE",
    role_analytique: "CONFORMITE_SEULE",
    niveau_verification: "VERIFIE",
    sensibilite: "NORMALE",
    obligatoire: true,
    actif: true,
    profils_applicables: ["PME", "PERSONNE_MORALE"],
    placeholder: "MA.BKO.2019.B.14820",
    piece_justificative_attendue: "Extrait RCCM du Greffe du Tribunal",
  },
  {
    id: "c_ca_annuel",
    code: "chiffre_affaires_annuel",
    libelle: "Chiffre d'Affaires Annuel (FCFA)",
    section_id: "sec_activite_pme",
    type_donnee: "MONTANT",
    categorie: "FINANCIER",
    temporalite: "SERIE_TEMPORELLE",
    role_analytique: "VARIABLE_CANDIDATE",
    niveau_verification: "VERIFIE",
    sensibilite: "FINANCIERE",
    obligatoire: true,
    actif: true,
    profils_applicables: ["PME", "PERSONNE_MORALE", "COMMERCANT"],
    placeholder: "Ex: 45 000 000",
    piece_justificative_attendue: "Bilans financiers certifiés ou livre journal",
  },

  // SECTION LOGEMENT & MENAGE (AVEC RÈGLE CONDITIONNELLE !)
  {
    id: "c_type_logement",
    code: "statut_logement",
    libelle: "Statut d'Occupation du Logement",
    section_id: "sec_menage",
    type_donnee: "CHOIX_SIMPLE",
    categorie: "MENAGE",
    temporalite: "VALEUR_ACTUELLE",
    role_analytique: "SEGMENTATION",
    niveau_verification: "DECLARE",
    sensibilite: "PERSONNELLE",
    obligatoire: true,
    actif: true,
    profils_applicables: ["SALARIE", "AGRICULTEUR", "COMMERCANT"],
    options: ["PROPRIETAIRE", "LOCATAIRE", "FAMILIAL", "LOGEMENT_FONCTION"],
  },
  {
    id: "c_loyer_mensuel",
    code: "loyer_mensuel_charges",
    libelle: "Montant du Loyer Mensuel (FCFA)",
    section_id: "sec_menage",
    type_donnee: "MONTANT",
    categorie: "FINANCIER",
    temporalite: "VALEUR_ACTUELLE",
    role_analytique: "ENTREE_REGLE",
    niveau_verification: "DECLARE",
    sensibilite: "FINANCIERE",
    obligatoire: true,
    actif: true,
    profils_applicables: ["SALARIE", "AGRICULTEUR", "COMMERCANT"],
    placeholder: "Ex: 75 000",
    // RÈGLE CONDITIONNELLE : Afficher seulement si statut_logement == "LOCATAIRE" !
    regle_affichage: {
      champ_source: "statut_logement",
      operateur: "==",
      valeur: "LOCATAIRE",
      action: "afficher",
    },
    piece_justificative_attendue: "Quittance de loyer ou contrat de bail",
  },

  // SECTION DEMANDE DE CREDIT
  {
    id: "c_montant_demande",
    code: "montant_credit_sollicite",
    libelle: "Montant du Crédit Sollicité (FCFA)",
    section_id: "sec_demande",
    type_donnee: "MONTANT",
    categorie: "FINANCIER",
    temporalite: "PHOTOGRAPHIE_T0",
    role_analytique: "ENTREE_REGLE",
    niveau_verification: "DECLARE",
    sensibilite: "FINANCIERE",
    obligatoire: true,
    actif: true,
    profils_applicables: ["TOUS"],
    placeholder: "Ex: 2 500 000",
  },
  {
    id: "c_duree_mois",
    code: "duree_remboursement_mois",
    libelle: "Durée de Remboursement Souhaitée (Mois)",
    section_id: "sec_demande",
    type_donnee: "ENTIER",
    categorie: "FINANCIER",
    temporalite: "PHOTOGRAPHIE_T0",
    role_analytique: "ENTREE_REGLE",
    niveau_verification: "DECLARE",
    sensibilite: "FINANCIERE",
    obligatoire: true,
    actif: true,
    profils_applicables: ["TOUS"],
    placeholder: "Ex: 18",
  },
];
